### ISSUE TITLE
empty quoted string not identified correctly

### ISSUE THREAD

**Issue by alexu** [adzero/vscode-sievehighlight#1]
The following sieve snippet is valid from a syntax point of view, yet the empty quoted string "" is not identified as a quoted string.

```
if allof (
	header :contains  ["X-Some-Header"] [""]
) {
	fileinto  "SomeFolderName";
	stop;
}
```

Using vscode January 2021 on MacOS BigSur.

**Comment by adzero** [comment]
Hi @alexu . 

It should be fixed in the new 1.0.2 version I just published.
