### ISSUE TITLE
Prefix for line comments 

### ISSUE THREAD

**Issue by delano** [adzero/vscode-sievehighlight#4]
Hey thanks for this extension 🆒

When using the "Toggle Line Comment" command, the line is prefixed with `// ` rather than `# ` (toggling the multi-line comment uses `/* */` which is good):

![vscode-sieve-comments-20240619](https://github.com/adzero/vscode-sievehighlight/assets/1206/b26c7abe-21f4-4896-9a24-8d99897271f4)

At least in Protonmail's UI, lines starting will `//` are treated as errors. Is this something that can be fixed in this extension or is the issue elsewhere?

![Screenshot 2024-06-19 at 12 00 37](https://github.com/adzero/vscode-sievehighlight/assets/1206/0594e700-2885-4998-ae76-ad768da45f05)

**Comment by adzero** [comment]
Hi @delano, 

Comment line definiton was indeed wrong in Language configuration file. 
I fixed it and released a new 1.0.7 version. You can update it if not already done automatically by your VS Code. 

I close the issue.

**Comment by delano** [comment]
Right on. Thank you!
